---
default_language_version:
  python: python3
  node: "14.16.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.0dev
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        exclude: >
          (?x)^(
            packer/provision/local-docker.yaml
          )$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        exclude: >
          (?x)^(
            jenkins-config/global-vars-production.sh|
            jenkins-config/global-vars-sandbox.sh|
            packer/provision/local-docker.yaml
          )$
